### ISSUE TITLE
Use application.yml instead of application.properties

### ISSUE THREAD

**Issue by ghost** [tanafaso/tanafaso-backend#2]
Spring boot application properties can be defined using both file formats. [yaml and .properties](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html)

It seems that .yaml will be much more cleaner as fields will not be repeated.
As an example:
In application.properties:
```
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/azkar
spring.datasource.username=springuser
spring.datasource.password=password
```
In application.yaml:
```
spring:
    datasource:
        password: password
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/azkar
        username: springuser
```
